server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

api:
  security:
    token:
      secret: ${JWT_SECRET:d2daa60db2d5fc7f9a3cbbe503b7ebda1550c20ee5478ecbdf547751f6609769}