server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-repository: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF